### ISSUE TITLE
Add https://github.com/jdorn/json-editor

### ISSUE THREAD

**Issue by Donskelle** [energiekollektiv/saiv#48]

**Comment by simnh** [comment]
Hey,
 
denkst du das hier geht?

https://github.com/jdorn/json-editor

Sowie ich das verstehe, ließen sich dann ja einfach verschiedene typen mit vorgegenben attributen anlegen die dann einfach über ein frontend erstellt werden können..

das wäre mega cool

**Comment by Donskelle** [comment]
Ja, gerne nimmt mir viel Arbeit ab.

**Comment by simnh** [comment]
ja gucken wir mal wie es sich so macht, aber sieht doch ganz vielversprchend aus.,.
